use school;
select * from ICC_World_Cup;
-- now we want a table to be generated by the data where columns are
-- Team, Played_Matches, Win_Matches, Lose_Matches
(select Team1 from ICC_World_Cup
union all
select Team2 from ICC_World_Cup)
-- Now if we put count to this CTE we can easily found the matches the played by 
-- using group by
with CTE as
(select Team1 as Team,case when Team1=Winner then 1 else 0 end Win_flag from ICC_World_Cup
union all
select Team2 as Team,case when Team2=Winner then 1 else 0 end Win_flag from ICC_World_Cup
)
select Team,COUNT(Win_flag) as Played_Matches,Sum(Win_flag) as Winned_matches,
(COUNT(Win_flag)-Sum(Win_flag)) as Lose_Matches
from cte group by Team order by Winned_matches desc